import type { Metadata } from 'next';
import './globals.css';
import { clashDisplay, outfit } from '@/fonts/fonts';
import { Toaster } from '@/components/ui/sonner';
import { SessionProvider } from 'next-auth/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplay.variable} ${outfit.variable} min-h-svh antialiased`}
      >
        <SessionProvider>
          <Toaster richColors />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
