import type { Metadata } from 'next';
import './globals.css';
import { clashDisplay, outfit } from '@/fonts/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplay.variable} ${outfit.variable} min-h-svh antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
